In [5]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import math

In [6]:
def compute_glcm(image, distance, angle, levels=256):
 height, width = image.shape
 glcm = np.zeros((levels, levels), dtype=np.uint32)
 # Convert angle to offset
 dx = int(round(distance * math.cos(math.radians(angle))))
 dy = int(round(distance * math.sin(math.radians(angle))))
 for i in range(height):
    for j in range(width):
        i2, j2 = i + dy, j + dx
        if 0 <= i2 < height and 0 <= j2 < width:
            glcm[image[i, j], image[i2, j2]] += 1
            glcm[image[i2, j2], image[i, j]] += 1 # Symmetry
 
 # Normalize the GLCM
 glcm = glcm / np.sum(glcm)
 return glcm

In [7]:
image_path = './lenna.png'
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

In [8]:
# GLCM computation
distance = 1
angle = 0 # Example angle
print(compute_glcm(img, distance, angle)) #21BAI1210

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
